---
title: "Lung tissue Meta-analysis for COPD"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    css: mystyle.css
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(kableExtra)
library(tidyverse)
library(RColorBrewer)
library(metafor)
library(meta)
# devtools::install_github("klaukh/d3heatmap",force = T)
library(d3heatmap)
library(DT)
```


About {data-orientation=rows}
=====================================  

We performed a meta-analysis with lung tissue and blood datasets. The paper  can be found in [link]() and the code to generate the analysis is in [Github](https://github.com/AnaBVA/Meta-analysis_COPD).

The analysis was performed using the following datasets: 

Row
-------------------------------------
    
### Experiments in the Meta-analysis

    
```{r}
gse_table <- read.csv("2021-03-26_Step3_Summary.csv", row.names = 1)
gse_table <- gse_table[-10,]
kable(gse_table, caption = "GSE information") %>%
   kable_styling()
```


Heatmap {data-orientation=rows}
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r}
numericInput("q_cutoff", "Q-value cutoff:", value = 0.001,
              min = 0, max = 1, step = 0.001)

numericInput("i2_cutoff", "I2 value cutoff:", value = 0.40,
              min = 0, max = 0.1, step = 0.05)

numericInput("numexp_cutoff", "Number of minimum experiments:", value = 5,
              min = 0, max = 100, step = 5)


```


   
Row {.tabset .tabset-fade}
-------------------------------------

### Heatmap {data-height=1200}


```{r}
# Data
full_tables <- read_csv("2020-10-08_Step5_Full_Tables.csv")
meta <- read_csv("2021-03-01_Step6_meta-analysis.csv")
# View(meta %>% filter(qval < 0.5,I2 < 40,num_exp > 5))


FC <- str_subset(colnames(full_tables),"logFC")

# Heatmap
genesqval <-  reactive({
  meta %>% filter(qval.random <= input$q_cutoff, 
                  I2 <= input$i2_cutoff, 
                  num_exp >= input$numexp_cutoff)
})

topgenes <- reactive({
  data.frame(full_tables[which(full_tables$GENE.SYMBOL %in% genesqval()$genes),FC], 
                   row.names = genesqval()$genes)
})


#rownames(topgenes) <- genesqval$genes
  
renderD3heatmap({
  d3heatmap::d3heatmap(topgenes(),
            #Rowv = FALSE, #Colv=FALSE,
            col = rev(brewer.pal(3,"RdBu")),
            scale = "column",
            na.color = "#cfcccc")
})
```


### Q-values

  
```{r}
renderPlot({
  hist(genesqval()$qval.random, probability = TRUE, breaks = 30,
       xlab = "q-values", main = "Adjusted p-values")
  
  dens <- density(genesqval()$qval.random)
  lines(dens, col = "blue")
})
```



### Tau2

  
```{r}

renderPlot({
  hist(genesqval()$tau2, probability = TRUE, breaks = 30,
       xlab = "tau2 values", main = "Tau2")
  
  dens <- density(genesqval()$qval.random)
  lines(dens, col = "red")
})
```



### I2

  
```{r}

renderPlot({
  hist(genesqval()$I2, probability = TRUE, breaks = 30,
       xlab = "I2", main = "Measure of heterogeneity by I2")
  
  dens <- density(genesqval()$qval.random)
  lines(dens, col = "red")
})
```



Gene {data-orientation=rows}
=====================================  

### Table of genes {data-height=300}

Please select one gene to generate a forest and funnel plot by clicking the interested row. The image can be saved with right click -> Save Image As...

```{r}

output$gen <- DT::renderDataTable(
meta,
selection = 'single'
)
DT::dataTableOutput('gen')

```

Row
-------------------------------------


```{r}
## Get meta-analysis data

CI.R <- str_subset(colnames(full_tables),"CI.R")
CI.L <- str_subset(colnames(full_tables),"CI.L")

for(i in 1:length(CI.R)) {
  full_tables[str_c("SE_",gsub(".*_","",CI.R))] <- (full_tables[,CI.R]-full_tables[,CI.L]) /(2*1.96)
}

SE <- str_subset(colnames(full_tables),"SE_")
GSE <- gsub(".*_","",FC)

meta.analysis <- function(gs){
gene <-  full_tables[full_tables$GENE.SYMBOL == gs,]
#gene <-  na.omit(full_tables[full_tables$GENE.SYMBOL == gs,])
gene <- gene[!is.na(gene$GENE.SYMBOL),]

dat <- data.frame(
  yi = as.numeric(gene[,FC]),
  sei = as.numeric(gene[,SE]),
  n1i = as.numeric(gse_table$CONTROL),
  n2i = as.numeric(gse_table$COPD)
)

dat <- escalc(measure="ZCOR", yi=yi,sei=sei,n1i=n1i,n2i=n2i, data = dat) 

dat$study <- rownames(gse_table)
dat$country <- gse_table$COUNTRY

m1 <- metagen(TE = yi, 
                  seTE = sei, 
                  studlab = study, 
                  n.e = n2i, 
                  n.c = n1i, 
                  data = dat,
                  method.tau = "REML", 
                  prediction = TRUE,
                  sm= "MD",
                  comb.fixed = FALSE)
return(m1)
}


```

### Forest plot

  
```{r}

renderPlot({
  gene =  as.character(meta[input$gen_rows_selected,"genes"])
  m1 <- meta.analysis(gene)
  forest(m1,
       col.diamond = "blue",
       #leftcols = c("study"),
       #rightcols = c("ci", "w.random"),
       leftlabs =  c("Study","logFC","se",NA,NA),
       colgap.left = unit(5,"mm"),
       lab.e = "COPD",
       colgap.studlab = unit(-10,"mm"),
       ff.study.label = "bold",
       just = "center",
       xlab = gene,
       prediction = TRUE)
})

```


### Funnel plot

  
```{r}

renderPlot({
  gene =  as.character(meta[input$gen_rows_selected,"genes"])
  m1 <- meta.analysis(gene)
  funnel.meta(m1,psize = 1.8,cex = 1.8)
})

```

